### ISSUE TITLE
cmd/cacheserver: cacheserver started by upspin command ignores cmdflags in config.

### ISSUE THREAD

**Issue by gbbr** [upspin/upspin#455]
Version: devel (d02ded064e4584551f1801ba71d6c7b6a669918f)
OS: macOS / 64bit

The `upspin` command seems to ignore cacheserver related `cmdflags` from the config file. Here is an example config file I am using:

```yaml
username: <hidden>
storeserver: <hidden>
dirserver: <hidden>
packing: ee
cache: y
cmdflags:
  cacheserver:
    cachesize: 5000
```
Now, when I run the commands:
```sh
$ upspin get @/hello_world
hello world
$ ps | grep cacheserver
19534 ttys003    0:00.12 cacheserver -cachedir=/Users/Gabriel/upspin -log=info -writethrough=false -cachesize=5000000000 -config=/Users/Gabriel/upspin/config -addr=
```
I expect the shown `cachesize` to be 5000, but instead its using the default value.

I think the solution to this is simply calling `config.SetFlagValues` before the cacheserver process executes in `cacheutil.Start`, correct?

I'm happy to commit a CL for this considering this is indeed a bug.
